/**
 * Work Products Page
 *
 * Main page for browsing work products (files generated by AI agents)
 */

'use client';

import { useState, useEffect } from 'react';
import { motion } from 'framer-motion';
import { FolderOpen, Search, Filter } from 'lucide-react';
import { useWorkProductStore } from '@/store/work-product.store';
import { useEmployeeStore } from '@/store/employee.store';
import { WorkProductCard } from '@/components/WorkProduct';
import { Button } from '@/components/Button';
import { Input } from '@/components/Input';
import { Badge } from '@/components/Badge';
import { Card, CardContent } from '@/components/Card';
import styles from './page.module.css';

export default function WorkProductsPage() {
  const { workProducts, fetchWorkProducts, loading } = useWorkProductStore();
  const { employees, fetchEmployees } = useEmployeeStore();
  const [search, setSearch] = useState('');
  const [selectedEmployee, setSelectedEmployee] = useState<string>('all');

  useEffect(() => {
    fetchWorkProducts();
    fetchEmployees();
  }, [fetchWorkProducts, fetchEmployees]);

  const filteredProducts = workProducts.filter((product) => {
    const matchesSearch = product.filename.toLowerCase().includes(search.toLowerCase());
    const matchesEmployee = selectedEmployee === 'all' || product.employeeId === selectedEmployee;
    return matchesSearch && matchesEmployee;
  });

  const handleView = (product: any) => {
    // Open file preview modal
    console.log('View product:', product);
  };

  const handleDownload = (product: any) => {
    // Trigger download
    console.log('Download product:', product);
  };

  // Group products by date
  const groupedProducts = filteredProducts.reduce((acc, product) => {
    const date = new Date(product.createdAt).toLocaleDateString('en-US', {
      month: 'long',
      year: 'numeric',
    });
    if (!acc[date]) acc[date] = [];
    acc[date].push(product);
    return acc;
  }, {} as Record<string, typeof filteredProducts>);

  return (
    <div className={styles.page}>
      {/* Header */}
      <header className={styles.header}>
        <div className={styles.headerLeft}>
          <div className={styles.icon}>
            <FolderOpen size={24} />
          </div>
          <div>
            <h1 className={styles.title}>Work Products</h1>
            <p className={styles.subtitle}>Browse files generated by AI agents</p>
          </div>
        </div>
      </header>

      {/* Content */}
      <div className={styles.content}>
        {/* Filters */}
        <div className={styles.filters}>
          <div className={styles.searchWrapper}>
            <Search size={18} className={styles.searchIcon} />
            <Input
              placeholder="Search files..."
              value={search}
              onChange={(e) => setSearch(e.target.value)}
              fullWidth
            />
          </div>

          <select
            className={styles.filterSelect}
            value={selectedEmployee}
            onChange={(e) => setSelectedEmployee(e.target.value)}
          >
            <option value="all">All Employees</option>
            {employees.map((emp) => (
              <option key={emp.id} value={emp.id}>
                {emp.name}
              </option>
            ))}
          </select>
        </div>

        {/* Stats */}
        <div className={styles.stats}>
          <Badge variant="primary" size="sm">
            {filteredProducts.length} file{filteredProducts.length !== 1 ? 's' : ''}
          </Badge>
        </div>

        {/* Products Grid */}
        {filteredProducts.length > 0 ? (
          <div className={styles.grid}>
            {filteredProducts.map((product) => (
              <WorkProductCard
                key={product.id}
                product={product}
                onView={handleView}
                onDownload={handleDownload}
              />
            ))}
          </div>
        ) : (
          <div className={styles.empty}>
            <FolderOpen size={48} className={styles.emptyIcon} />
            <h3>No work products yet</h3>
            <p>
              Work products are files generated by AI agents during task execution.
              They will appear here once tasks start producing output.
            </p>
          </div>
        )}
      </div>
    </div>
  );
}
