/**
 * Work Products Service
 *
 * Part of TASK-5.2 - Work Product API
 *
 * Manages work products generated by AI agents during task execution.
 */

import { v4 as uuidv4 } from 'uuid';
import * as db from '../storage/db';
import * as fileStorage from '../storage/file-storage';

export interface WorkProduct {
  id: string;
  taskId?: string;
  employeeId?: string;
  filename: string;
  originalName: string;
  filepath: string;
  mimeType?: string;
  sizeBytes?: number;
  version: number;
  createdAt: number;
}

export interface CreateWorkProductInput {
  taskId?: string;
  employeeId: string;
  filename: string;
  originalName: string;
  mimeType?: string;
  sizeBytes?: number;
}

export interface CreateWorkProductFromFileInput {
  taskId?: string;
  employeeId: string;
  fileBuffer: Buffer;
  originalName: string;
  mimeType?: string;
}

/**
 * Create a new work product record
 */
export function createWorkProduct(input: CreateWorkProductInput): WorkProduct {
  const product: WorkProduct = {
    id: uuidv4(),
    taskId: input.taskId,
    employeeId: input.employeeId,
    filename: input.filename,
    originalName: input.originalName,
    filepath: `/storage/${input.filename}`,
    mimeType: input.mimeType,
    sizeBytes: input.sizeBytes,
    version: 1,
    createdAt: Date.now(),
  };

  // Store in database
  db.createWorkProduct({
    id: product.id,
    task_id: product.taskId,
    employee_id: product.employeeId,
    filename: product.filename,
    filepath: product.filepath,
    mime_type: product.mimeType,
    size_bytes: product.sizeBytes,
    version: product.version,
  });

  return product;
}

/**
 * Create a work product from a file buffer
 */
export async function createWorkProductFromFile(
  input: CreateWorkProductFromFileInput
): Promise<WorkProduct | null> {
  try {
    // Upload file to storage
    const folder = `work-products/${input.employeeId}`;
    const uploadResult = await fileStorage.uploadFile(
      input.fileBuffer,
      input.originalName,
      input.mimeType || 'application/octet-stream',
      { folder }
    );

    if (!uploadResult.success || !uploadResult.file) {
      console.error('[WorkProductService] File upload failed:', uploadResult.error);
      return null;
    }

    // Create work product record
    const product = createWorkProduct({
      taskId: input.taskId,
      employeeId: input.employeeId,
      filename: uploadResult.file.filename,
      originalName: input.originalName,
      mimeType: uploadResult.file.mimeType,
      sizeBytes: uploadResult.file.size,
    });

    console.log(`[WorkProductService] Created work product: ${product.id}`);
    return product;
  } catch (error: any) {
    console.error('[WorkProductService] Create from file failed:', error);
    return null;
  }
}

/**
 * Get work product by ID
 */
export function getWorkProduct(id: string): WorkProduct | null {
  const record = db.getWorkProductById(id);
  if (!record) return null;

  return {
    id: record.id,
    taskId: record.task_id || undefined,
    employeeId: record.employee_id,
    filename: record.filename,
    originalName: record.filename,
    filepath: record.filepath,
    mimeType: record.mime_type || undefined,
    sizeBytes: record.size_bytes || undefined,
    version: record.version,
    createdAt: record.created_at,
  };
}

/**
 * Get all work products for an employee
 */
export function getWorkProductsByEmployee(employeeId: string): WorkProduct[] {
  const records = db.getWorkProductsByEmployee(employeeId);
  return records.map((record) => ({
    id: record.id,
    taskId: record.task_id || undefined,
    employeeId: record.employee_id,
    filename: record.filename,
    originalName: record.filename,
    filepath: record.filepath,
    mimeType: record.mime_type || undefined,
    sizeBytes: record.size_bytes || undefined,
    version: record.version,
    createdAt: record.created_at,
  }));
}

/**
 * Get all work products for a task
 */
export function getWorkProductsByTask(taskId: string): WorkProduct[] {
  const records = db.getWorkProductsByTask(taskId);
  return records.map((record) => ({
    id: record.id,
    taskId: record.task_id || undefined,
    employeeId: record.employee_id,
    filename: record.filename,
    originalName: record.filename,
    filepath: record.filepath,
    mimeType: record.mime_type || undefined,
    sizeBytes: record.size_bytes || undefined,
    version: record.version,
    createdAt: record.created_at,
  }));
}

/**
 * Delete a work product
 */
export async function deleteWorkProduct(id: string): Promise<boolean> {
  try {
    const product = getWorkProduct(id);
    if (!product) return false;

    // Delete from file storage
    await fileStorage.deleteFile(product.filename);

    // Delete from database
    db.deleteWorkProduct(id);

    console.log(`[WorkProductService] Deleted work product: ${id}`);
    return true;
  } catch (error: any) {
    console.error('[WorkProductService] Delete failed:', error);
    return false;
  }
}

/**
 * Get file download URL
 */
export function getDownloadUrl(productId: string): string | null {
  const product = getWorkProduct(productId);
  if (!product) return null;

  return `/api/work-products/${productId}/download`;
}

/**
 * List all work products (with optional filters)
 */
export function listWorkProducts(filters?: {
  employeeId?: string;
  taskId?: string;
}): WorkProduct[] {
  let records: db.WorkProduct[];

  if (filters?.taskId) {
    records = db.getWorkProductsByTask(filters.taskId);
  } else if (filters?.employeeId) {
    records = db.getWorkProductsByEmployee(filters.employeeId);
  } else {
    // Get all - need to add this function to db.ts
    records = [];
  }

  return records.map((record) => ({
    id: record.id,
    taskId: record.task_id || undefined,
    employeeId: record.employee_id,
    filename: record.filename,
    originalName: record.filename,
    filepath: record.filepath,
    mimeType: record.mime_type || undefined,
    sizeBytes: record.size_bytes || undefined,
    version: record.version,
    createdAt: record.created_at,
  }));
}
